import Footer from "@/src/app/components/Footer";
import Header from "@/src/app/components/Header";
import { ReportPipelineProvider } from "@/src/lib/context/ReportPipelineContext";
import { cn } from "@/src/lib/utils";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `${geistSans.variable} ${geistMono.variable}`,
          "bg-background",
        )}
      >
        <Header />
        <div className="min-h-screen space-y-6">
          {/* Increased padding to account for fixed header with blur */}
          <div className="pt-17">
            <ReportPipelineProvider>{children}</ReportPipelineProvider>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
