import Footer from "@/src/app/components/Footer";
import Header from "@/src/app/components/Header";
import { cn } from "@/src/lib/utils";
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Fira_Code, Outfit } from "next/font/google";
import "./globals.css";

const geistSans = Outfit({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Fira_Code({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `${geistSans.variable} ${geistMono.variable}`,
          "bg-background",
        )}
      >
        <div className="min-h-screen space-y-6">
          <Header />
          {/* Increased padding to account for fixed header with blur */}
          <div className="pt-17">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
