import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cn } from "../lib/utils";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(`${geistSans.variable} ${geistMono.variable}`)}>
        <Header />
        <div className="min-h-screen space-y-6 bg-gradient-to-br from-orange-100 via-pink-100 to-red-100">
          <div className="pt-17">
            {/* Increased padding to account for fixed header with blur */}
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
